# Generated by Django 5.0 on 2023-12-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banking_name', models.CharField(default='', max_length=250)),
                ('account_no', models.CharField(default='', max_length=250)),
                ('password', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=250)),
                ('hall_type', models.CharField(max_length=250)),
                ('total_seat', models.CharField(max_length=250)),
            ],
        ),
    ]
